app = "carwash2o"
primary_region = "arn" # Можно поменять на ru-central1, если Fly.io поддерживает РФ-регионы

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[experimental]
  auto_rollback = true

# Volume for persistent storage (SQLite)
[[mounts]]
  destination = "/app/backend/data"
  source = "carwash_data"

# Single-machine mode: start.sh runs both backend and bot via concurrently

[[services]]
  internal_port = 3000
  protocol = "tcp"
  force_https = true
  http_checks = []
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = true
