app = "carwash2o"
primary_region = "waw" # Можно поменять на ru-central1, если Fly.io поддерживает РФ-регионы

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[experimental]
  auto_rollback = true

# Volume for persistent storage (SQLite)
[[mounts]]
  destination = "/app/backend/data"
  source = "carwash_data"

[# Define two process groups: web app and bot]
[processes]
  app = "/app/start.sh app"
  bot = "/app/start.sh bot"

[[services]]
  processes = ["app"]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
