app = "carwash2o"
primary_region = "waw" # Можно поменять на ru-central1, если Fly.io поддерживает РФ-регионы

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
